default_index:
    path:     /
    defaults: { _controller: "BackendBundle:Default:index" }
    methods:  GET

default_pruebas:
    path:     /pruebas
    defaults: { _controller: "BackendBundle:Default:pruebas" }
    methods:  GET

default_login:
    path:     /login
    defaults: { _controller: "BackendBundle:Default:login" }
    methods:  POST